baseURL: https://nserbin.com/

locale: en-us

title: "Nicolas Serbin's"

module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icons/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts


# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    locale: en
    label: English
    weight: 1
  es:
    locale: es
    label: Spanish
    weight: 2

# Force a locale to be use, really useful to develop the application ! Should be commented in production, the "weight" should rocks.
# DefaultContentLanguage: en

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 10
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

# Generate a root robots.txt with the sitemap location.
enableRobotsTXT: true

# Site parameters
params:
  # Background image of the landing page
  background: /images/site/back.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    main: /images/site/nicolas-logo.png
    inverted: /images/site/nicolas-logo.png
    dark: /images/site/nicolas-logo.png
    favicon: /images/site/nicolas-favicon.png

  # GitHub repo of your site
  gitRepo: https://github.com/NSerbin/nserbin.github.io
  # Default branch of your Git repo
  gitBranch: source
  # Configure various features of this theme

  topNavbar:
    maxVisibleSections: 9

  features:

    theme:
      enable: true
      services:
        # enable light theme. default "true"
        light: true
        # enable dark theme. default "true"
        dark: true
        # can be either light, dark or system. default "system"
        default: dark

    # Enable and configure portfolio
    portfolio:
      enable: true

    # Enable and configure blog posts
    blog:
      enable: true
      showAuthor: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true
        email: true

    # Enable & configure "Notes" features
    notes:
      enable: false

    analytics:
      enable: true
      services:
        enable: true
        # Google Analytics
        google:
          id: G-KKTMP7TCHN
          respectDoNotTrack: true

    # Enables copy code button
    copyCodeButton:
      enable: true

    # Enable Support
    support:
      enable: false

    # s cify whether you want to show Table of Contents in reading page
    toc:
      enable: true  
    
    # Show tags under the post title
    tags:
      enable: true
      on_card: true

    flags:
      enable: true
      flagOverwrites:
        - languageCode: es
          countryCode: ar
    # If you want to use different country flag for a language, specify them here.

    # Enable this to use `embed-pdf` shortcode.
    embedpdf:
      enable: false

  # Provide footer configuration.
  footer:
    enable: true
    # Compact footer with copyright and contact links.
    template: custom-footer.html
