baseURL: https://nserbin.github.io

languageCode: en-us

title: "Nicolas Serbin's Blog"

module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1
  es:
    languageName: Spanish
    weight: 2

# Force a locale to be use, really useful to develop the application ! Should be commented in production, the "weight" should rocks.
# DefaultContentLanguage: bn

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Background image of the landing page
  background: /images/site/background.jpg

  # GitHub repo of your site
  gitRepo: https://github.com/NSerbin/nserbin.github.io
  # Default branch of your Git repo
  gitBranch: source
  # Configure various features of this theme

  topNavbar:
    maxVisibleSections: 5

  features:

    theme:
      # enable light theme. default "true"
      light: true
      # enable dark theme. default "true"
      dark: true
      # can be either light, dark or system. default "system"
      defaultTheme: true 

    # Enable and configure portfolio
    portfolio:
      enable: true

    # Enable and configure blog posts
    blog:
      enable: true
      showAuthor: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true
        email: true

    # Enable & configure "Notes" features
    notes:
      enable: true

    # specify whether you want to show Table of Contents in reading page
    toc:
      enable: true  
    
    # Show tags under the post title
    tags:
      enable: true
      on_card: true

    flags:
      enable: true
      flagOverwrites:
        - languageCode: es
          countryCode: ar
    # If you want to use different country flag for a language, specify them here.


  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
      customMenus: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true

    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".
    newsletter:
      enable: false

    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: true
